import "server-only";

import { Prisma } from "@/generated/prisma/client";
import { WorkspaceRole, WorkspaceType } from "@/generated/prisma/enums";

import { recordAudit } from "../audit/audit-log";
import type { GuardedPrismaClient } from "../db/prisma";
import { AppError } from "../errors/app-error";
import { parseInput } from "../validation/parse";
import {
  createWorkspaceInputSchema,
  type CreateWorkspaceInput,
} from "../workspaces/workspace-input";

import { createTenantContext, isUuid } from "./context";

export interface CreatedWorkspace {
  readonly id: string;
  readonly name: string;
  readonly slug: string;
}

/** The creator. Always the authenticated session user — never a value from input. */
export interface WorkspaceCreator {
  readonly id: string;
}

function slugTaken(): AppError {
  return new AppError("CONFLICT", {
    message: "Workspace slug already in use",
    fields: [{ path: "slug", code: "slug_taken" }],
    metadata: { resource: "workspace" },
  });
}

function isUniqueViolation(error: unknown): boolean {
  return error instanceof Prisma.PrismaClientKnownRequestError && error.code === "P2002";
}

/**
 * Creates a tenant: the workspace, the creator's OWNER membership and the
 * `workspace.created` audit entry, in one transaction — either all three exist or none.
 *
 * The server fixes everything that is not user content: type BUSINESS (AGENCY/client
 * workspaces are Phase 14), the creator from the session, role OWNER. Runs on the
 * tenant-guarded client. The tenant context for the audit entry is built from the
 * membership row this transaction just inserted, which is why this lives in the
 * tenancy layer.
 *
 * Errors: VALIDATION_FAILED for invalid input; CONFLICT with a `slug` field error
 * (`slug_taken`) when the slug is in use — including by a soft-deleted workspace.
 */
export async function createWorkspace(
  db: GuardedPrismaClient,
  creator: WorkspaceCreator,
  rawInput: CreateWorkspaceInput,
): Promise<CreatedWorkspace> {
  if (!isUuid(creator.id)) {
    throw new AppError("INTERNAL", { message: "Invalid workspace creator id" });
  }
  const input = parseInput(createWorkspaceInputSchema, rawInput, "workspace");

  return db.$transaction(async (tx) => {
    const workspace = await tx.workspace
      .create({
        data: {
          name: input.name,
          slug: input.slug,
          defaultLocale: input.defaultLocale,
          type: WorkspaceType.BUSINESS,
        },
        select: { id: true, name: true, slug: true, type: true, defaultLocale: true },
      })
      .catch((error: unknown) => {
        // The id is generated by Postgres, so the slug is the only unique value here.
        throw isUniqueViolation(error) ? slugTaken() : error;
      });

    const membership = await tx.workspaceMember.create({
      data: { workspaceId: workspace.id, userId: creator.id, role: WorkspaceRole.OWNER },
      select: { workspaceId: true, userId: true, role: true },
    });

    const ctx = createTenantContext(membership);
    await recordAudit(tx, ctx, {
      action: "workspace.created",
      entityType: "workspace",
      entityId: workspace.id,
      metadata: {
        slug: workspace.slug,
        type: workspace.type,
        defaultLocale: workspace.defaultLocale,
        ownerRole: membership.role,
      },
    });

    return { id: workspace.id, name: workspace.name, slug: workspace.slug };
  });
}
